# Generated by Django 3.1.7 on 2021-02-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210219_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
