# Generated by Django 3.1.7 on 2021-02-21 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210221_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
