# Generated by Django 3.1.6 on 2021-02-19 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='urlIn',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'urlin',
            },
        ),
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('summaryofarticle', models.TextField()),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.urlin')),
            ],
        ),
    ]
