# Generated by Django 3.1.6 on 2021-02-19 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_summary_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summaryofarticle', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='summary',
        ),
    ]
